-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `my_practice_catalog`;
USE SCHEMA `default`;

-- COMMAND ----------

SELECT * from orders_bronze;

-- COMMAND ----------

select * from customers_bronze;

-- COMMAND ----------

select * from payments_bronze;

-- COMMAND ----------

select * from orders_silver_cleaned;

-- COMMAND ----------

select * from customers_silver_cleaned;

-- COMMAND ----------

select * from payments_silver_cleaned;

-- COMMAND ----------

select * from orders_silver;

-- COMMAND ----------

select * from customers_silver;

-- COMMAND ----------

select * from payments_silver;

-- COMMAND ----------

select * from top_customers_gold;

-- COMMAND ----------

